name: Release Gem

on:
  workflow_call:

env:
  GEMSPEC: "*.gemspec"

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to push tags

      - name: Resolve gemspec filename
        id: gemspec
        run: |
          FILE=$(ls $GEMSPEC | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Extract version from gemspec
        id: version
        run: |
          VER=$(ruby -e "spec = Gem::Specification.load('${{ steps.gemspec.outputs.file }}'); puts spec.version")
          echo "version=v$VER" >> $GITHUB_OUTPUT

      - name: Create tag if missing
        run: |
          TAG=${{ steps.version.outputs.version }}

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists â€” skipping."
            exit 0
          fi

          echo "Creating tag $TAG"
          git tag "$TAG"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: auto_tag
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Resolve gemspec filename
        id: gemspec
        run: |
          FILE=$(ls $GEMSPEC | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Extract gem metadata
        id: gem
        run: |
          NAME=$(ruby -e "spec = Gem::Specification.load('${{ steps.gemspec.outputs.file }}'); puts spec.name")
          VER=$(ruby -e "spec = Gem::Specification.load('${{ steps.gemspec.outputs.file }}'); puts spec.version")
          FILE="${NAME}-${VER}.gem"

          echo "name=$NAME"  >> $GITHUB_OUTPUT
          echo "version=$VER" >> $GITHUB_OUTPUT
          echo "gemfile=$FILE" >> $GITHUB_OUTPUT

      - name: Build gem
        run: gem build "${{ steps.gemspec.outputs.file }}"

      - name: Configure RubyGems credentials
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

      - name: Push to RubyGems
        run: gem push "${{ steps.gem.outputs.gemfile }}"
